chrismhampson/rails-airbnb-clone

- Gemfile.lock
- app/controllers/cakes_controller.rb
- app/models/cake.rb
- app/models/order.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20211115161127_create_cakes.rb
- db/migrate/20211115161914_create_orders.rb
- db/schema.rb
- test/controllers/cakes_controller_test.rb
- test/models/cake_test.rb
- test/models/order_test.rb
Hi guys! Could you check these changes, please.
> created cakes controller, order + cake models

- db/migrate/20211116113453_add_baker_to_users.rb
- db/schema.rb
Can you check the schema looks ok?
> Added baker boolean to user model

- db/migrate/20211116122236_add_photo_url_to_cake.rb
- db/migrate/20211116122312_add_avatar_url_to_user.rb
- db/schema.rb
Added photo/avatar urls to respective models. Thanks for checking!
> Added photo and avatar urls to models

- app/controllers/cakes_controller.rb
> Cakes controller

- app/views/cakes/index.html.erb
- app/views/cakes/show.html.erb
- app/views/pages/home.html.erb
Hi guys - here's a template for the show and index views minus the html/bootstrap, just so we can check our pages are displaying on Heroku :)
> show and index views

- Gemfile.lock
- app/controllers/pages_controller.rb
Temporarily removing auth requirement so we can view all pages on Heroku app.
> Authentication change

- app/controllers/cakes_controller.rb
- app/controllers/pages_controller.rb
> Fixed authentication

- db/seeds.rb
> created seeds file

- app/controllers/orders_controller.rb
- test/controllers/orders_controller_test.rb
Hi guys! Could you check the orders controller over, please?
> orders controller

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/cakes/_navbar.html.erb
- app/views/cakes/index.html.erb
- app/views/cakes/show.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
please review my code tomorrow morning, thank youu
> fixed landing page, made index page, started show page

- app/views/pages/home.html.erb
Hi guys - have fixed the main page link to index
> fixed link to index

- app/controllers/orders_controller.rb
- app/views/cakes/_form.html.erb
- app/views/cakes/new.html.erb
- app/views/orders/_form.html.erb
- app/views/orders/new.html.erb
- db/migrate/20211117121723_add_portions_to_orders.rb
- db/schema.rb
> Added forms

- app/views/cakes/index.html.erb
Index page images linked through to show page
> image-clickthrough

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/cakes/_index.scss
- app/assets/stylesheets/cakes/_show.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/cakes/_navbar.html.erb
- app/views/cakes/index.html.erb
- app/views/cakes/show.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
> fixed show page, index page, and seeds file

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_orders_new.scss
- app/controllers/orders_controller.rb
- app/views/orders/_form.html.erb
- app/views/orders/new.html.erb
- app/views/orders/order_confirmed.html.erb
- config/routes.rb
I've added an order confirmation page, updated the controller accordingly. I've also updated and styled the order form page.
> Confirmation page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/cakes/_import.scss
- app/assets/stylesheets/cakes/_index.scss
- app/assets/stylesheets/cakes/_show.scss
- app/views/cakes/_navbar.html.erb
- app/views/cakes/index.html.erb
- app/views/cakes/show.html.erb
- db/seeds.rb
changed some things on the stylesheets and added baker name (may be conflict so we can just keep master version)
> added baker name, stylesheets

- app/controllers/orders_controller.rb
- app/views/orders/order_confirmed.html.erb
Cosmetic changes to confirm page + link
> Confirmation page adjusted

- db/migrate/20211118115839_add_default_value_to_users.rb
- db/schema.rb
> added baker default value of false

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/cakes/_show.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/cakes_controller.rb
- app/models/cake.rb
- app/views/cakes/_form.html.erb
- app/views/cakes/_navbar.html.erb
- app/views/cakes/index.html.erb
- app/views/cakes/show.html.erb
- app/views/orders/_form.html.erb
- config/cloudinary.yml
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20211118123025_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
> implemented cloudinary, fixed cards, can upload photo as a baker

- app/models/order.rb
- app/models/user.rb
Check validations for user and order models
> Validations

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/cakes/_index.scss
- app/controllers/cakes_controller.rb
- app/models/cake.rb
- app/views/cakes/index.html.erb
Have finished the search function (name, description and baker).
> pg search and button inline

- app/assets/stylesheets/pages/_orders_new.scss
- app/views/cakes/show.html.erb
- db/seeds.rb
Fixed the search by baker function.
> search fixed

- app/assets/stylesheets/pages/_home.scss
- app/controllers/application_controller.rb
- app/views/cakes/_form.html.erb
- app/views/cakes/_navbar.html.erb
- app/views/devise/registrations/new.html.erb
log out added, user field now mandatory on sign up so it can be pulled by show page, homepage button, add cake form tweaks.
> Form fixing and tweaks

- app/views/cakes/_form.html.erb
> fixed create cake button

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/orders/_index.scss
- app/assets/stylesheets/orders/_order_confirmed.scss
- app/views/cakes/index.html.erb
- app/views/orders/new.html.erb
- app/views/orders/order_confirmed.html.erb
> fixed bugs and button for oder confirmed

- app/controllers/application_controller.rb
Have fixed the Devises auth syntax
> auth fixed
